// =====================================================================
//  transcribe.mjs — bakes the reference FF9-style MIDIs into the game's
//  step-sequencer format (16 steps/bar) and writes js/music-data.js.
//  Each piece = 3 MIDI tracks: melody / continuous arpeggio / lament bass.
//  Run:  node tools/transcribe.mjs
// =====================================================================
import fs from 'node:fs';

function parse(file) {
  const buf = fs.readFileSync(new URL('../assets/midi/' + file, import.meta.url));
  let p = 0; const rd = n => { let v = 0; for (let i = 0; i < n; i++) v = (v << 8) | buf[p++]; return v; };
  const vlq = () => { let v = 0, b; do { b = buf[p++]; v = (v << 7) | (b & 0x7f); } while (b & 0x80); return v; };
  p = 4; rd(4); rd(2); const ntrk = rd(2), div = rd(2); let bpm = 0; const tracks = [];
  for (let t = 0; t < ntrk; t++) {
    p += 4; const len = rd(4); const end = p + len; let tick = 0, run = 0; const notes = [], on = {};
    while (p < end) {
      tick += vlq(); let ev = buf[p]; if (ev < 0x80) ev = run; else { p++; run = ev; } const hi = ev & 0xf0;
      if (ev === 0xff) { const m = buf[p++]; const l = vlq(); if (m === 0x51) bpm = Math.round(60000000 / ((buf[p] << 16) | (buf[p + 1] << 8) | buf[p + 2])); p += l; }
      else if (ev === 0xf0 || ev === 0xf7) { p += vlq(); }
      else if (hi === 0x90) { const k = buf[p++], v = buf[p++]; if (v > 0) (on[k] = on[k] || []).push(tick); else if (on[k] && on[k].length) notes.push({ k, s: on[k].shift(), e: tick }); }
      else if (hi === 0x80) { const k = buf[p++]; p++; if (on[k] && on[k].length) notes.push({ k, s: on[k].shift(), e: tick }); }
      else if (hi === 0xc0 || hi === 0xd0) p++; else p += 2;
    }
    p = end; if (notes.length) { notes.sort((a, b) => a.s - b.s); tracks.push(notes); }
  }
  return { bpm, div, tracks };
}

function transcribe(file) {
  const { bpm, div, tracks } = parse(file);
  const stepTicks = div / 4;                 // a 16th note
  const [melT, arpT, bassT] = tracks;
  const lastStep = Math.max(...tracks.flat().map(n => Math.round(n.e / stepTicks)));
  const BARS = Math.ceil(lastStep / 16); const LEN = BARS * 16;
  const mel = Array(LEN).fill(0), melDur = Array(LEN).fill(0), arp = Array(LEN).fill(0), bass = Array(LEN).fill(0);
  for (const n of melT) { const s = Math.round(n.s / stepTicks); if (s < LEN) { mel[s] = n.k; melDur[s] = Math.max(1, Math.round((n.e - n.s) / stepTicks)); } }
  for (const n of arpT) { const s = Math.round(n.s / stepTicks); if (s < LEN) arp[s] = n.k; }
  for (const n of bassT) { const s = Math.round(n.s / stepTicks); if (s < LEN) bass[s] = n.k; }
  // chord per bar (for the string pad) from the arpeggio's root/3rd/5th, dropped an octave into a warm register
  const bars = [];
  for (let b = 0; b < BARS; b++) {
    const r = arp[b * 16] || arp[b * 16 + 2] || 60, th = arp[b * 16 + 2] || r, fi = arp[b * 16 + 4] || r;
    bars.push([r - 12, th - 12, fi - 12, r]);
  }
  return { bpm, bars: BARS, mel, melDur, arp, bass, chords: bars };
}

const out = { ff9_dorian: transcribe('ff9_dorian.mid'), ff9_demo: transcribe('ff9_demo.mid') };
const fmt = a => '[' + a.join(',') + ']';
let js = '// AUTO-GENERATED by tools/transcribe.mjs from assets/midi/*.mid — do not hand-edit.\n';
js += '// Note-for-note transcriptions of the reference FF9-style pieces (melody / arpeggio / lament bass).\n';
js += 'window.MUSIC_DATA = {\n';
for (const k in out) { const d = out[k];
  js += `  ${k}: { bpm: ${d.bpm}, bars: ${d.bars},\n`;
  js += `    mel: ${fmt(d.mel)},\n    melDur: ${fmt(d.melDur)},\n    arp: ${fmt(d.arp)},\n    bass: ${fmt(d.bass)},\n`;
  js += `    chords: [${d.chords.map(fmt).join(',')}] },\n`;
}
js += '};\n';
fs.writeFileSync(new URL('../js/music-data.js', import.meta.url), js);
console.log('wrote js/music-data.js');
for (const k in out) console.log(`  ${k}: ${out[k].bpm}bpm, ${out[k].bars} bars, ${out[k].mel.filter(x => x).length} mel notes, ${out[k].arp.filter(x => x).length} arp notes`);
